[2025-04-03T14:27:59.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 manual__2025-04-03T14:27:58.863621+00:00 [queued]>
[2025-04-03T14:27:59.389+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 manual__2025-04-03T14:27:58.863621+00:00 [queued]>
[2025-04-03T14:27:59.389+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-03T14:27:59.399+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): spark_task2> on 2025-04-03 14:27:58.863621+00:00
[2025-04-03T14:27:59.403+0000] {standard_task_runner.py:57} INFO - Started process 1126 to run task
[2025-04-03T14:27:59.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'POC_orange_data2', 'spark_task2', 'manual__2025-04-03T14:27:58.863621+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/pass_data.py', '--cfg-path', '/tmp/tmp2uaqfag8']
[2025-04-03T14:27:59.408+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask spark_task2
[2025-04-03T14:27:59.439+0000] {task_command.py:416} INFO - Running <TaskInstance: POC_orange_data2.spark_task2 manual__2025-04-03T14:27:58.863621+00:00 [running]> on host 44552ddc80b1
[2025-04-03T14:27:59.605+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='POC_orange_data2' AIRFLOW_CTX_TASK_ID='spark_task2' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T14:27:58.863621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T14:27:58.863621+00:00'
[2025-04-03T14:27:59.606+0000] {logging_mixin.py:154} INFO - Checking files in: /opt/***/
[2025-04-03T14:27:59.606+0000] {logging_mixin.py:154} INFO - Checking files in: /opt/***/data
[2025-04-03T14:28:02.378+0000] {logging_mixin.py:154} INFO - loading data
[2025-04-03T14:28:02.378+0000] {logging_mixin.py:154} INFO - Checking files in: /opt/***/data
[2025-04-03T14:28:02.378+0000] {logging_mixin.py:154} INFO - Files: []
[2025-04-03T14:28:03.267+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pass_data.py", line 29, in spark_processing
    df = spark.read.csv(files, header=True, inferSchema=True, sep="|")
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [UNABLE_TO_INFER_SCHEMA] Unable to infer schema for CSV. It must be specified manually.
[2025-04-03T14:28:03.279+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=POC_orange_data2, task_id=spark_task2, execution_date=20250403T142758, start_date=20250403T142759, end_date=20250403T142803
[2025-04-03T14:28:03.291+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task spark_task2 ([UNABLE_TO_INFER_SCHEMA] Unable to infer schema for CSV. It must be specified manually.; 1126)
[2025-04-03T14:28:03.306+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-03T14:28:03.322+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
